### ISSUE TITLE
Landscape mode only covers 1/2 the screen width

### ISSUE THREAD

**Issue by fbara** [workshirt/WSCoachMarksView#14]
Can you please update so that it covers the entire screen in landscape mode on iPhone 5S?  If not, can you please let me know what I have to change to get it to cover the entire width?

Thanks.
![ios_simulator_-_iphone_retina__4-inch_64-bit____ios_7_1](https://cloud.githubusercontent.com/assets/5705015/3662311/b2fc185e-11c9-11e4-8342-c822cadff793.png)

**Comment by gask** [comment]
I'm also looking for an update in this same topic.
My controller that is using the WSCoachMarksView supports both orientations and when I change to Landscape, the CoachMarksView doesn't adapt to the new screen layout. I tried changing the coachMarksView frame using setFrame, but the view's frame remained unchanged.

Can you help us with that?

**Comment by fbara** [comment]
This appears to be working in Landscape now.  I don't know if it was an update or not but I no longer have this issue.  I'm going to close the issue but feel free to re-open if anyone still has the same problem.
