### ISSUE TITLE
Display over UINavigation controller?

### ISSUE THREAD

**Issue by maxwell-fraser** [workshirt/WSCoachMarksView#2]
I have a UINaviationController at the top of my app and it would be sweet if this overlaid on top of that so I could explain my icons.

**Comment by DataZombies** [comment]
This works.
    UIWindow *topWindow = [[[UIApplication sharedApplication].windows sortedArrayUsingComparator:^NSComparisonResult(UIWindow *win1, UIWindow *win2) {
      return win1.windowLevel - win2.windowLevel;
    }] lastObject];
    self.topView = [[topWindow subviews] lastObject];
    WSCoachMarksView *coachMarksView = [[WSCoachMarksView alloc] initWithFrame: self.topView coachMarks:coachMarks];
